INSERT INTO USER (USERNAME, PASSWORD) VALUES ('maria', 'password');
INSERT INTO USER (USERNAME, PASSWORD) VALUES ('joao', '12345');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('maria', 'USER');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('maria', 'ADMIN');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('joao', 'USER');