INSERT INTO USER (USERNAME, PASSWORD) VALUES ('maria', '$2a$11$DbpOiIBXnR1RW/BCcJ5q3eK8Y6rsST9xyJAAS2LU51w6AyNTjmy0S');
INSERT INTO USER (USERNAME, PASSWORD) VALUES ('joao', '$2a$11$H/1RaTuMxpGXwfrw982wPu9CTFVz6LEEg9WdNQ5MZd72dXeuZZQXu');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('maria', 'USER');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('maria', 'ADMIN');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('joao', 'USER');