INSERT INTO USER (USERNAME, PASSWORD) VALUES ('maria', '$2a$11$DSZBrCztYg54.ZCV/9rbM.scPpDVhVWUGJXBbZ0YcZ7omgId7UUwy');
INSERT INTO USER (USERNAME, PASSWORD) VALUES ('joao', '$2a$11$DSZBrCztYg54.ZCV/9rbM.scPpDVhVWUGJXBbZ0YcZ7omgId7UUwy');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('maria', 'USER');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('maria', 'ADMIN');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('joao', 'USER');